{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.database.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  clusterIP: None
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
  - name: postgres
    port: {{ .Values.database.service.port }}
    targetPort: postgres
    protocol: TCP
{{- end }}
